name: rtkrig
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - pandas
  - geopandas
  - scikit-gstat
  - requests
  - gdal
  - folium
  - branca
  - numpy
  - matplotlib
  - gunicorn
  - kafka-python
  - apscheduler