name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "basic-kriging/kriging_app/*", "basic-app-pipe/kriging_app/*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag basic-kriging-app:$(date +%s)
